### ISSUE TITLE
node cache version update

### ISSUE THREAD

**Issue by damienleroux** [jpodwys/cache-service-node-cache#4]
I can see that node [cache version](https://github.com/mpneuried/nodecache) is 4.2 now. 

What do you think about making `node-cache` a peer of this project to let developers choose their version and have the last fixes from `node-cache`? 

Thank you!!

**Comment by jpodwys** [comment]
That sounds like a great idea. Are you interested in making the PR? If so, it makes sense to me that the unit tests would run against the most recent major release of `node-cache`.

As a note, I'm not certain `cache-service-node-cache` still provides any compelling value. Since writing it, I've released the following:

* `cache-service-cache-module` for in-memory caching in both node and the browser
* `cache-service-redis` for distributed caching

If you're taking advantage of `node-cache`'s feature set outside of what I expose with `cache-service-node-cache`'s API, then it's certainly providing value to you. However, if you're using only the public API I provide (meaning nothing from `nodeCacheModule.db`), then I recommend switching to the other cache modules I've mentioned.

The in-memory solution I mentioned has no dependencies and can therefore be used in node and the browser. It also supports persisting to `localStorage` and `sessionStorage` out of the box. The redis solution I mentioned will allow you to persist data between node restarts.

The advantages these other libs have, combined with `cache-service-node-cache`'s [low download count](https://npm-stat.com/charts.html?package=cache-service-node-cache) and lack of activity, have caused me to consider deprecating `cache-service-node-cache` in favor of `cache-service-cache-module`.

Are you open to switching to `cache-service-cache-module`, or do you have a compelling reason I should not deprecate this repo?

**Comment by damienleroux** [comment]
Hello.

Yes I tried first `cache-service-cache-module` but it didn't fit my use case. I needed to have several caches, not one global cache. This ways it is easy for me to delete or create caches that are dedicated to one source. With `cache-service-node-cache`, I can create several caches.

I see other reasons to not deprecate this repo: 

- [`node-cache`](https://github.com/mpneuried/nodecache) seems still active and have enough stars to have a cache service for it.
- Having a direct access to `.db` can be useful. For example, on a server side rendering server that uses the cache, I created one API to serialize as JSON the content of one cache (useful to debug or create external tests) and one api to delete a cache (useful for reseting the cache state before testing the project)

Concerning `node-cache` update, i'll make a PR soon if that's ok for you?

**Comment by jpodwys** [comment]
Yes, a PR sounds good!

**Comment by jpodwys** [comment]
As I've stated before, I'm happy to review and merge a PR.

On an unrelated note, I would appreciate some clarification about one comment.

> I tried first cache-service-cache-module but it didn't fit my use case. I needed to have several caches, not one global cache.

You can have multiple instances of `cache-service-cache-module`--it is not global. Please help me understand if I've missed something.

**Comment by damienleroux** [comment]
When trying `cache-service-cache-module` and debugging after the first cache update, I was not able to see were data really was (like `.db`). This leads me to the code [`var cache`](https://github.com/jpodwys/cache-service-cache-module/blob/master/cacheModule.js#L31). I must admit that I read it too fast and didn't see it was enclosed by the function. So I was wrong about `cache-service-cache-module` providing only one global cache.

That being said, why not create `cache` on `this` instead? I guess you want to avoid the cache being mutated without the provided functions. But, in my case, I needed to serialize the whole cache (for selenium testing purpose) and it was simpler with `cache-service-node-cache` to read `.db`. Let me know what you think of it :)

**Comment by jpodwys** [comment]
`cache-service-node-cache` and `cache-service-redis` expose a `.db` property to grant users access to the underlying cache instance each of them wraps. Therefore, if you're serializing `cacheServiceNodeCache.db`, you're serializing the entire `node-cache` instance it wraps, not just the data it houses. Unlike its sibling repos, `cache-service-cache-module` is not a wrapper around an existing cache implementation and therefore exposes no `.db`.

If serializing the entire cache instance meets your needs, then you can do the same thing with `cache-service-cache-module`. However, I'm happy to add a public getter that returns a cloned instance of the cache's contents. For brevity, I would use `JSON.parse(JSON.stringify(data))`. This means functions and date objects stored in the cache would not be cloned correctly, but I'm fine with that change because `cache-service-redis` already does it that way and I [already plan](https://github.com/jpodwys/cache-service-cache-module/pull/11) to do it that way with `cache-service-cache-module`.

Ultimately, I'm interested in doing what's best. If people find legitimate, unique value in `cache-service-node-cache`, I'll keep it around. Thank you for all your feedback!

**Comment by damienleroux** [comment]
Actually I am serializing only  `db.data` from node cache to get the cache content.

You said:

>  I'm happy to add a public getter that returns a cloned instance of the cache's contents

do you mean a public getter to get en entire cache content? I read your [commit](https://github.com/jpodwys/cache-service-cache-module/pull/11/files): it looks like it returns the clone object but only for one key

**Comment by jpodwys** [comment]
Yes, I was saying that I would return the entire cache object. So all keys and values currently stored. By referencing that commit, I was just showing the strategy I would use to clone the entire cache since it does have some gotchas.

However, cloning `cache-service-cache-module`'s internal cache may be problematic as it removes expired keys lazily, meaning I only evaluate whether a key has expired when a user asks for it. Therefore the getter would either have to remove all expired keys first, or it would return potentially expired data.

At this point, I'm happy for you to stick with `cache-service-node-cache` since it fits your needs. Thank you for kicking around some ideas with me!
